# La información a continuación se puede encontrar en el repositorio de github en
# https://github.com/FranciscoRatti/FileFX/blob/main/README.md en la sección de configuración.

# Los iconos soportados son los de las fuentes nerd, los puedes buscar en https://www.nerdfonts.com/cheat-sheet

# En este archivo se encuentra la configuración principal de la aplicación. Su sintaxis es CLAVE=VALOR, a continuacion
# se muestran las posibles propiedades seguidas del valor predeterminado, puedes modificar los valores.


# GENERAL --------------------------------------------------------------------------------------------------------------

# Tema, debe coincidir con el nombre del archivo .css en "~/.config/filefx/"
theme=default.css

# Comando a ejecutar al abrir una terminal.
terminal=xterm

# Ubicación donde se guardan las plantillas de archivos que se usan al crear un nuevo archivo.
templates_dir=~/Templates

# Si es true se guarda el tamaño de la ventana al cerrarse.
save_bounds=true

# Si es true guarda la última ubicación.
save_path=true

# Si es true guarda el último item seleccionado.
save_selection=true


# TOP PANE -------------------------------------------------------------------------------------------------------------

# Define los botones que aparecerán en el TopPane. La sintaxis es [{boton;icono},{boton;icono},...]. Los posibles
# valores son BACKWARD, FORWARD, PARENT, SEARCH, CLEAN, RELOAD.
top_buttons=[{BACKWARD;},{FORWARD;},{PARENT;󰙅},{SEARCH},{CLEAN;󰃢},{RELOAD;}]


# RIGHT PANE -----------------------------------------------------------------------------------------------------------

# Si es true se guarda el tamaño del panel derecho en "init_values.properties".
save_right_width=false

# Define si se muestra el RightPane al iniciar.
show_right_pane=true

# Dentro del RightPane hay una miniatura, si es true en caso de seleccionar una imagen esta se mostrará, si es false se
# muestra siempre el icono.
show_miniatura=true

# Si es true, pinta las miniaturas con el mismo color que el icono.
fill_miniatura_like_icon=true

# Si es true se muestran los archivos dentro de directorios en las miniaturas. Puede influir en el rendimiento.
show_inside_directories=false

# Si es true se muestran las líneas de texto de archivos lejibles en las miniaturas.
show_inside_files=true


# BOTTOM PANE ----------------------------------------------------------------------------------------------------------

# Define los botones que aparecen en el BottomPane. Los posibles valores son ORDER, FILTER.
bottom_buttons=[ORDER,FILTER]

# Define los iconos de los botones para cambiar el orden. El orden es [NAME,DATE,SIZE,MIME].
order_icons=[,,󰲎,]


# LEFT PANE ------------------------------------------------------------------------------------------------------------

# Si es true se guarda el tamaño del panel izquierdo.
save_left_width=false

# Define si se muestran los "Lugares" en el LeftPane.
show_places=true

# Define ubicaciones personalizadas que aparecerán en Lugares en el LeftPane. Su sintaxis es
# [{nombre;icono;dirección},{nombre;icono;dirección},...].
places=[{Home;;~/},{Descargas;;~/Downloads/},{Documentos;󱔗;~/Documents/},{Imagenes;;~/Images/},{Papelera;;~/.local/share/Trash/files/},{Config;;~/.config/filefx/}]

# Sí es true aparecerán los discos y particiones en el LeftPane.
show_devices=true

# Define la etiqueta de particiones específicas, el resto tendrá el nombre predeterminado. La sintaxis es
# [{punto de montaje;nombre},...].
partition_labels=[{/;Raiz},{/boot/efi;Boot}]

# Si es true se muestran las particiones que no están montadas en el LeftPane.
show_unmounted=false

# Define el icono del botón de desmontar.
unmount_icon=󰚦


# CENTER PANE ----------------------------------------------------------------------------------------------------------

# Si es true se muestran los directorios primero.
is_directory_first=true

# Si es true se muestran los archivos y directorios que empiezan por "."
show_hidden=true

# Si es true aparecerá un directorio llamado "." que hace referencia a la ubicacion actual.
show_this=true

# Si es true aparece un directorio llamado ".." que hace referencia al directorio padre.
show_parent=true

# Si es true los nombres de los archivos tendrán el mismo color que sus iconos, si es false el color será el definido
# por la propiedad [unknow] en "colors_binding.properties".
fill_text_file_like_icon=false

# Lo mismo que el anterior pero con los directorios.
fill_text_dir_like_icon=true

# Define el orden predeterminado de los archivos y directorios. Los posibles valores son NAME, DATE, SIZE o MIME.
default_order=NAME

# Define el orden para directorios específicos. Su sintaxis es [{path;orden},{path;orden},...]. El segundo valor puede
# ser NAME, DATE, SIZE o MIME.
custom_order=[{~/Downloads/;DATE},{~/Images/;DATE},{~/Videos/;DATE},{trash/;DATE}]

# Define las columnas del CenterPane. Los posibles valores son PERMISSIONS, OWNER, GROUP, SIZE, MODIFIED, CREATED y TYPE.
columns=[SIZE]


# CONTEXT MENU ---------------------------------------------------------------------------------------------------------

# Define los items del menu contextual y su orden. Los posibles valores son BACKWARD, FORWARD, OPEN, OPEN_WITH,
# CREATE_FILE, CREATE_DIR, CREATE_LINK, RENAME, PERMISSIONS, COPY, CUT, PASTE, RESTORE, TRASH, REMOVE, EXTRACT,
# COMPRESS, SHELL, ADMIN y SEPARATOR.
context_menu_items=[BACKWARD,FORWARD,SEPARATOR,OPEN,OPEN_WITH,CREATE_FILE,CREATE_DIR,CREATE_LINK,SEPARATOR,RENAME,PERMISSIONS,SEPARATOR,COPY,CUT,PASTE,SEPARATOR,RESTORE,TRASH,REMOVE,EXTRACT,COMPRESS,SHELL,ADMIN]

# Define los iconos del menu contextual. El orden es el mismo de "context_menu_items".
context_menu_icons=[,, ,󰷏,󰷏,,,, ,󰘎,, ,,󰆐,󰆒, ,,,,󰏖,󰏗,,]

# Si es true revisará el portapapeles del sistema antes de abrir el menu contextual, si no lo hará cuando se presione el
# item "pegar".
check_clipboard_paste=true