#
#Sat Sep 19 17:40:23 ART 2026
height=527.0
init_path=/home/fran-linux/Documents/Programacion/Proyectos/TodoImpreso/src/main/java/com/todoimpreso/caja/
init_selection=Caja.java
left_width=130.0
right_width=200.0
width=950.0
