cut=ctrl+x
copy=ctrl+c
paste=ctrl+v
remove=ctrl+delete
trash=delete
rename=f4

up=up
open=enter,right
down=down
parent=backspace,left
up_step=page up
down_step=page down
first=home
last=end

select_up=shift+up
select_down=shift+down
select_up_step=shift+page up
select_down_step=shift+page down
select_first=shift+home
select_last=shift+end
deselect_all=esc

back=ctrl+z
forward=ctrl+y

show_menu=context menu,ctrl+space
show_menu_create=n
change_show_right_pane=space
change_show_hidden=h
change_permissions=p
update_all=f5

focus_path=s
focus_filter=f
focus_inside=i
save_inside=ctrl+s

open_shell=ctrl+t