# La información a continuación se puede encontrar en el repositorio de github en
# https://github.com/FranciscoRatti/FileFX/blob/main/README.md en la sección de configuración.

# En este archivo se encuentran asignadas las combinaciones de teclado de la aplicación. Su sintaxis es CLAVE=VALOR, a
# continuacion se muestran las posibles propiedades seguido del valor predeterminado, puedes modificar los valores.
# No distingue mayusculas ni minusculas y se pueden definir varias separadas por coma. Los nombre de cada tecla son los
# mismos que aparecen en la API de JavaFX en
# https://docs.oracle.com/en/java/java-components/javafx/21/docs/javafx.graphics/javafx/scene/input/KeyCode.html

# Cortar.
cut=ctrl+x

# Copiar.
copy=ctrl+c

# Pegar.
paste=ctrl+v

# Eliminar permanentemente.
remove=ctrl+delete

# Mandar a la papelera.
trash=delete

# Renombrar.
rename=f4

# Arriba.
up=up

# Abrir o entrar.
open=enter,right

# Abajo.
down=down

# Atras.
parent=backspace,left

# Arriba 3 posiciones.
up_step=page up

# Abajo 3 posiciones.
down_step=page down

# Primer elemento.
first=home

# Ultimo elemento.
last=end

# Seleccionar arriba.
select_up=shift+up

# Seleccionar abajo.
select_down=shift+down

# Seleccionar arriba 3 posiciones.
select_up_step=shift+page up

# Seleccionar abajo 3 posiciones.
select_down_step=shift+page down

# Seleccionar hasta el primero.
select_first=shift+home

# Seleccionar hasta el ultimo.
select_last=shift+end

# Deseleccionar todo.
deselect_all=esc

# Cerrar
close=esc,q

# Muestra la ventana goto
goto=g

# Deshacer.
backward=ctrl+z

# Rehacer.
forward=ctrl+y

# Abrir una terminal aqui.
open_shell=ctrl+t

# Mostrar menu contextual, equivalente a hacer click derecho.
show_menu=context menu,ctrl+space

# Crear archivo o directorio.
show_menu_create=n

# Pasarle el foco a la barra de busqueda.
focus_path=s

# Pasarle el foco a la barra de filtro.
focus_filter=f

# Si "show_inside_files" es true, le pasa el foco al interior del archivo.
focus_inside=i

# Si "show_inside_files" es true, guarda los cambios del interior del archivo seleccionado.
save_inside=ctrl+s

# Actualizar todo.
update_all=f5

# Mostrar o esconder RightPane.
change_show_right_pane=space

# Cambiar mostrar archivos ocultos.
change_show_hidden=h

# Cambiar permisos.
change_permissions=p