init_directory=$HOME/Documents
width=1200
height=700

is_directory_first=true
show_hidden=true
show_miniatura=false
show_right_pane=true

# Right pane
right_pref_width=200

# Left pane
show_places=true
show_devices=true

# Optimizacion
disable_paste_item=false