terminal=kitty
save_bounds=true
save_path=true
save_selection=true

#TOP PANE
top_buttons=[{back;},{forward;},{parent;󰙅},{search},{clean;󰃢},{reload;}]

#RIGHT PANE
right_width=200.0
show_right_pane=true
show_miniatura=true
fill_miniatura_like_icon=true

#LEFT PANE
show_places=true
places=[{Home;;~/},{Descargas;;~/Downloads/},{Documentos;󱔗;~/Documents/},{UTN;󰑴;~/Documents/UTN/Actual_Cuatrimestre},{Imagenes;;~/Images/},{Papelera;;~/.local/share/Trash/files/}]
show_devices=true

#CENTER PANE
is_directory_first=true
show_hidden=true
show_this=true
show_parent=true
fill_text_file_like_icon=false
fill_text_dir_like_icon=true

#CONTEXT MENU
context_menu_icons=[󰷏,󰷏,,,󰘎,,󰆐,󰆒,,,,]
check_clipboard_paste=false
