is_directory_first=true
show_hidden=true
check_clipboard_paste=false
terminal=kitty

save_bounds=true
save_path=true
save_selection=true

#TOP PANE
top_buttons={back,forward,parent,search,clean,reload}

#RIGHT PANE
right_width=200.0
show_right_pane=true
show_miniatura=true

#LEFT PANE
show_places=true
places={Home;;~/},{Descargas;;~/Downloads/},{Documentos;󱔗;~/Documents/},{Imagenes;;~/Images/},{Papelera;;~/.local/share/Trash/files/}
show_devices=true

#CONTEXT MENU
context_menu_icons={󰷏,󰷏,,,󰘎,,󰆐,󰆒,,,,}