cut=d
copy=y
paste=p
remove=ctrl+delete
trash=delete
rename=f4

up=up
open=right,enter
down=down
parent=left,backspace
up_step=page up
down_step=page down
first=home
last=end

select_up=shift+up
select_down=shift+down
select_up_step=shift+page up
select_down_step=shift+page down
select_first=shift+home
select_last=shift+end

back=u
forward=r

open_shell=ctrl+t
show_menu=context menu,ctrl+space
show_menu_create=n
focus_path=l
focus_filter=f
deselect_all=esc
update_all=f5
change_show_right_pane=space
change_show_hidden=h